# Generated by Django 4.1.6 on 2023-05-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("target_language", models.CharField(max_length=10)),
                ("source_language", models.CharField(default="auto", max_length=10)),
                ("translated_text", models.TextField()),
            ],
        ),
    ]
